resources:
  - kind: file
    selector:
      query: (.file.content |  has("components")) or (.file.content | has("al_number"))
      files:
        - path: "**.yaml" # Suboptimal, da potentiell andere Dateien als Projekte erfasst werden
        - repos:
            - ilab-aks-central-dev-projects
            - nordlb-aks-central-dev-projects
            - nordlb-aks-central-acc-projects
            - nordlb-aks-central-prod-projects
    port:
      itemsToParse: >-
        [     
          if .file.content  | has("components") then
            .file.content.components.terraform | to_entries[] |
            .value.vars.config
          elif (.file.content | has("al_number")) then
            .file.content
          else
            null
          end
        ]
      entity:
        mappings:
          blueprint: '"project_yaml"'
          title: (.file.name  | split(".")[0]) + "-" + (.repo.name | split("-")[3])
          identifier: >-
            def tenant_name: .repo.name | split("-")[0];
            def cluster_name: .repo.name | split("-")[2];
            def stage_name: .repo.name | split("-")[3];
            def project_name: .file.name | split(".")[0];

            tenant_name + "-" + cluster_name + "-" + stage_name + "-" + project_name
          team: .item.ad_group
          relations:
            project_to_it_object: .item.al_number
          properties:
            data: .item
