resources:   
  - kind: file  
    selector:
      query: (.file.content |  has("components")) or (.file.content | has("al_number")) 
      files: 
        - path: "**.yaml" # Suboptimal, da potentiell andere Dateien als Projekte erfasst werden
        - repos:
            - test-repo 
    port: 
      itemsToParse: >-  
        [     
          if .file.content | has("components") then
          (try .file.content.components.terraform catch null) as $terraform |
          if $terraform != null and ($terraform | type) == "array" then
            $terraform[] | .vars.config
          else
            null
          end
                elif (.file.content | has("al_number")) then
                  .file.content
                else
                  null
                end
        ]
      entity: 
        mappings:
          blueprint: '"project_yaml"'
          title: (.file.name  | split(".")[0]) + "-" + .repo.name 
          identifier: (.file.name  | split(".")[0]) + "-" + .repo.name 
          team: .item.ad_group
          relations:
            project_to_it_object: .item.al_number
          properties:
            data: .item 
